apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc }}

