apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-issue-operator.metricsServiceName" . }}
  namespace: {{ include "github-issue-operator.namespace" . }}
  labels:
    {{- include "github-issue-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "github-issue-operator.selectorLabels" . | nindent 4 }}
