apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "github-issue-operator.namespace" . }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "github-issue-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- include "github-issue-operator.labels" . | nindent 4 }}

