apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-issue-operator.secretName" . }}
  namespace: {{ include "github-issue-operator.namespace" . }}
  labels:
    {{- include "github-issue-operator.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc }}
