apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-issue-operator.serviceAccountName" . }}
  namespace: {{ include "github-issue-operator.namespace" . }}
  labels:
    {{- include "github-issue-operator.labels" . | nindent 4 }}
